# SERVER DATA
SERVER_PORT = 12000
SERVER_ADDRESS = '127.0.0.1'

# ENIGMA DATA
alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
rotor_combination = 'DMTWSILRUYQNKFEJCAZBPGXOHV'
reflector_combination = 'EJMZALYXVBWFCRQUONTSPIKHGD'
